### ISSUE TITLE
Popup BR - Notification à 10 poireaux sur 10

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#101]
![image](https://cloud.githubusercontent.com/assets/12863317/20861514/69f36536-b992-11e6-97be-77d09ddc3732.png)
J'ai toujours la popup à 9/10 mais le BR s'est fait il y a 8 minutes

**Comment by 5pilow** [comment]
Done in https://github.com/leek-wars/leek-wars-client/commit/7448f8ea337faf138b06fa19b57296ccf55e742a
