### ISSUE TITLE
Rajouter le panel d'émojis pour les commentaires

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#103]
![image](https://cloud.githubusercontent.com/assets/12863317/20867889/b0a18618-ba4e-11e6-8da1-71fc76b7c40e.png)

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/70cc08e7a486c219bf5bac39aa662610bbdcb53e
https://github.com/leek-wars/leek-wars-client/commit/0ec07926ab9af913829a576a7be518c311137b19
