### ISSUE TITLE
market.js ligne 314, traduire les catégories de puces

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#104]

**Comment by PerthuisQuentin** [comment]
C'est fait :)
#107

**Comment by Becold** [comment]
https://github.com/leek-wars/leek-wars-client/blob/master/http/script/market.js#L313
Ce tableau typeLang. Sauf que ce tableau n'est utilisé nulpart donc il me semble qu'il peut être supprimé !

**Comment by PerthuisQuentin** [comment]
Ouais, il aurait pu être retiré dans la PR. Oops :)

**Comment by 5pilow** [comment]
Done in https://github.com/leek-wars/leek-wars-client/pull/192
