### ISSUE TITLE
Potager - Compteur de combat incorrect

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#109]
![image](https://cloud.githubusercontent.com/assets/12863317/20993523/2c035cd4-bceb-11e6-8b67-3f4b5548360e.png)

Solo: Min/min (il manque le max)
Eleveur : Min/min (il manque le max)
Équipe : Ok
Battle royal : Min plus grand que max

**Comment by 5pilow** [comment]
C'est normal pour Solo et Éleveur, c'est les combats cumulables.
Pour les battles royales il y a une erreur par contre

**Comment by Becold** [comment]
Pour Solo et Éleveur, le deuxième chiffre devrait rester le nombre de combat maximum non ? C'est à dire respectivement 80 et 20.

**Comment by 5pilow** [comment]
Non car la limite normale est de 40 et 10 ;)

**Comment by 5pilow** [comment]
C'est corrigé pour les BR.
