### ISSUE TITLE
Popup BR - Fermer la popup ferme aussi toute autre popup

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#110]
1. **Rejoindre** la queue d'un BR 
2. Aller sur **l'éditeur** et ouvrir l'onglet **Paramètre** 
3. **Quitter** la queue du BR en fermant la popup BR -> L'onglet paramètre se ferme aussi 

4. **Rejoindre** la queue d'un BR
5. Aller sur la **page d'un poireau** et ouvrir l'interface des **Potions**
6. 3 popups s'ouvrent

![image](https://cloud.githubusercontent.com/assets/12863317/21004781/63b8c7bc-bd32-11e6-8cf2-fba7e4643ca6.png)

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/516061448b4163eb118d3a0047729432fe4f9570
