### ISSUE TITLE
/doc! apparait sur deux lignes

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#115]
![image](https://cloud.githubusercontent.com/assets/16955502/21072733/bcd93cc8-becc-11e6-9dc4-f8ca88be3951.png)

Peut-être lié à : 
```
.chat-message-messages {
    word-break: break-word;
}
```
(Du moins quand je l'enlève, ça résout le problème. Mais je sais pas si ça casse autre chose.)

**Comment by 5pilow** [comment]
C'est à cause de l'userscript ^^
