### ISSUE TITLE
Forum Team - La nom de la team ne s'affiche pas dans un topic

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#117]
https://github.com/leek-wars/leek-wars-client/blob/master/http/view/forum_topic.html#L6

![image](https://cloud.githubusercontent.com/assets/12863317/21124697/bb0ed072-c0e0-11e6-9f6f-6ca80f3a911f.png)

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/ed00120610ab819fc14120173c76124f18419133
