### ISSUE TITLE
[Potager] Mauvais message d'erreur (IA manquante)

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#119]
![image](https://cloud.githubusercontent.com/assets/16955502/21205284/a83ac146-c25b-11e6-88af-e6d75dd37350.png)

On a le message d'erreur "Pas d'adversaires à ta taille" :
- Si le poireau n'a pas d'IA équipée
- Si l'IA équipée sur le poireau est sauvegardée avec une erreur.

**Comment by PerthuisQuentin** [comment]
J'suis dessus : [https://github.com/PerthuisQuentin/leek-wars-client/tree/gardenErrors](url)
Me reste à trouver pourquoi ça veut toujours pas s'afficher...

**Comment by Becold** [comment]
Peut-être que l'api renvoie le mauvais message d'erreur

**Comment by PerthuisQuentin** [comment]
Nan, via l'API j'ai les bonnes infos. C'est niveau html/css que le changement ne se fait pas. Je sais pas encore pourquoi ^^

**Comment by PerthuisQuentin** [comment]
Fonctionnel via les APIs.
A améliorer avec des retours d'erreurs sur les APIs get-*-opponents.
Faire quelque chose de similaire en éleveur/farmer (BR ?)

**Comment by PerthuisQuentin** [comment]
Up ? :B

**Comment by PerthuisQuentin** [comment]
A fermer :)
