### ISSUE TITLE
[combat] Améliorations de l'affichage du combat

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#12]
- Poireaux plus petits
- Mode tactique plus light
- Moins d'animations de poireaux
- Remplacer les états feu et gaz par des icônes au dessus des entités

**Comment by Shakadak** [comment]
* Redimensionner l'animation des lasers pour être plus représentatifs de leurs portées
![Traverse toute la carte](https://i.imgur.com/XfcnBM1.png)

**Comment by 5pilow** [comment]
Fait pour les 4 premiers points, reste les lasers

**Comment by Shakadak** [comment]
* Animation et son lors de coups critique. (Un point d'exclamation vert qui apparaît brièvement au dessus du lanceur par exemple.)

**Comment by 5pilow** [comment]
![laser_fix](https://user-images.githubusercontent.com/5173005/71561094-4a55d980-2a72-11ea-9122-8b2f28000cd0.png)
C'est fait pour les lasers, pour les coups critiques je fais une autre issue ;)
