### ISSUE TITLE
Chat - Ajouter le markdown `texte`

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#120]
`var test = 123;`
ou
![image](https://cloud.githubusercontent.com/assets/12863317/21296175/d00594b4-c565-11e6-8408-558436ea2f0d.png)
_(screen de discord)_

**Comment by jeuxjeux20** [comment]
Aussi ajouter le markdown \`\`\`code\`\`\` tant qu'on y est :p

**Comment by Becold** [comment]
Il faut d'abord ajouter l'implémentation des sauts de ligne dans le chat ;p

**Comment by 5pilow** [comment]
`texte` => code inline

```
code sur
plusieurs lignes
```

**Comment by jeuxjeux20** [comment]
\`code\`
`\`\`\plusieurs
lignes
woaw
j'adore`\`\`\`

**Comment by 5pilow** [comment]
C'est fait !
