### ISSUE TITLE
Equipe - Créer une équipe ne supprime pas les candidatures vers une autre équipe

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#122]
Cette personne a voulu rejoindre notre équipe : 
![image](https://cloud.githubusercontent.com/assets/12863317/21444412/6a55fb9a-c8ad-11e6-9aeb-a92aaceeeacc.png)

Mais quelques jours plus tard, elle a crée sa propre équipe : 
![image](https://cloud.githubusercontent.com/assets/12863317/21444429/8a494efc-c8ad-11e6-9dd4-858e7453d8c7.png)

Mais sa candidature est restée dans notre équipe

**Comment by 5pilow** [comment]
Corrigé :)
