### ISSUE TITLE
Profil - Avatar qui ne s'actualise pas

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#123]
(Après l'envoi d'un nouvel avatar pour son profil)
![image](https://cloud.githubusercontent.com/assets/12863317/21394365/9f98890a-c798-11e6-95ea-bd2da9817280.png)

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/52957e879b69de46dc757c2789c1b40f7656b857 + https://github.com/leek-wars/leek-wars-client/commit/9a74a5aba18e4b099bf1c1c0443779fd4e25ee64

**Comment by 5pilow** [comment]
J'ai pas actualisé dans le chat, seuls les nouveaux messages seront actualisés, pas les anciens
