### ISSUE TITLE
Notifs sidebar - Cliquer sur "notifications" fait disparaitre la date et la scroll-bar

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#124]
Avant : 
![image](https://cloud.githubusercontent.com/assets/12863317/21427535/6bd65648-c855-11e6-9cf8-6a3fa0ab8191.png)

Après avoir cliquer sur Notifications : 
![image](https://cloud.githubusercontent.com/assets/12863317/21427546/79ef6fa8-c855-11e6-988e-48a7b0e29fe5.png)

**Comment by 5pilow** [comment]
C'est déjà corrigé avec https://github.com/leek-wars/leek-wars-client/commit/da984400f428058ad1141bfb840207c1e500f3b8 :)
