### ISSUE TITLE
Chat - Liste des commandes

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#125]
L'idée serait de rajouter une liste des commandes qui existent. Parce que pour les moments, le seul moyen de les connaitre est de les connaître par coeur. Certaines commandes (/modo, etc...) pourraient pourquoi pas rester secrètes, comme easters eggs. :)

Cette idée a été proposée plusieurs fois par des joueurs et elle me semble intéressantes. J'ai pris des screens de discord pour pouvoir visualiser l'idée (car ils ont cette feature).

Liste des commandes :
![image](https://cloud.githubusercontent.com/assets/12863317/21438600/2eba4cc6-c88a-11e6-884b-2fa735899262.png)

En plus, pour les commandes qui demandent un paramètre (tel que /doc:mot ou /wiki:mot), on pourrait ajouter d'autres propositions liés à la recherche : 
![image](https://cloud.githubusercontent.com/assets/12863317/21438671/9339f0ac-c88a-11e6-94a2-47881fb0d2c0.png)

**Comment by 5pilow** [comment]
Done by Ref
