### ISSUE TITLE
[Potager] Mauvais maximum pour les combats solo

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#127]
![](http://puu.sh/sYdbr/8958ad14ba.jpg)

Il devrait avoir 0/20 et non 0/40.
De même, quand il récupère ses combats journaliers, il passe à 20/40.

**Comment by Becold** [comment]
![image](https://cloud.githubusercontent.com/assets/12863317/21444838/56b56f08-c8b2-11e6-8ea8-29f4080c9225.png)

**Comment by Becold** [comment]
Devrait être fermé car le système des compteurs a été modifié depuis 46301548f8ce26fdde886382374330859a002adc
