### ISSUE TITLE
[API] La page des APIs n'affiche plus rien.

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#130]
![image](https://cloud.githubusercontent.com/assets/16955502/21528622/2bb78d96-cd34-11e6-8c2e-a7db125ba1e5.png)

**Comment by k-artorias** [comment]
Le json retourné par https://leekwars.com/api/service/get-all/$ n'est pas bon : 
`TeamController::serviceChangeEmblem{"success":true,"services":[{"id":6 ...`

**Comment by 5pilow** [comment]
C'est corrigé
