### ISSUE TITLE
[Tests] Duplication des poireaux lors d'un combat de test

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#133]
https://leekwars.com/forum/category-3/topic-8505

![image](https://cloud.githubusercontent.com/assets/16955502/21575236/4b0a61fe-cf06-11e6-920a-65c285e7009c.png)

En relançant un combat de test via le bouton "Refaire un combat" disponible sur le rapport, il arrive que les poireaux soient dupliqués.
Apparemment, c'est seulement à l'affichage, si on recharge le combat, ce n'est plus le cas.

**Comment by Dagal** [comment]
Salut,

Si on tape plusieurs fois sur le bouton 'refaire un combat' la multiplication se fait de manière exponentielle. Donc ça recopie tous les poireaux de la session sans effacer les précédents. Ce sont des poireaux fantôme car ils ne font rien et le combat se termine correctement quand l'un des 2 'réel' est mort.

**Comment by Becold** [comment]
J'ai tenté de reproduire le bug mais je n'y arrive pas.
Si tu as une explication exacte des étapes à suivre pour le reproduire, je suis preneur!

**Comment by PerthuisQuentin** [comment]
C'est pas systématique, mais en général, j'arrive à le reproduire sans trop de peine, perso.
Simplement, tu lance un combat de test, tu va au rapport, et tu utilise le bouton "refaire un combat".
Plusieurs fois si nécessaire.

Je viens d'essayer. Au bout de 3-4 essais, je me suis retrouvé avec un combat de test avec les poireaux en triple.

**Comment by Becold** [comment]
En suivant la procédure, je suis tombé sur un autre bug, je ne l'avais jamais vu : 
![image](https://cloud.githubusercontent.com/assets/12863317/23160646/91ce05ec-f827-11e6-86d0-147a4cab258a.png)
![image](https://cloud.githubusercontent.com/assets/12863317/23160706/c10a537e-f827-11e6-9c4e-1d4f254d0502.png)

Il me semble avoir vu des commits il y a quelques temps, peut-être (ou peut-être pas) lié à ça : 
4d447064e64a7886049872499a028bdcf854dbed
d7c90935e2164340c691af84fb14e846989c38a1

**Comment by Becold** [comment]
Fixes 0b6bb0265156895a1bdeff38d1163775bf4aade0
Cette issue peut être fermée
