### ISSUE TITLE
Stuck on "Loading fight"

### ISSUE THREAD

**Issue by MDMCK10** [leek-wars/leek-wars-client#137]
Example: http://i.imgur.com/f5fohaC.gif

Note: Refreshing seems to fix this, but i don't really know why this is happening.

**Comment by jeuxjeux20** [comment]
~~Cuz u didn't activated windows~~

**Comment by MDMCK10** [comment]
jeux can you not

**Comment by Becold** [comment]
Ca a été fixé. C'était le bouton "Refaire un combat" qui était rebindé plusieurs fois par un eventlistener. Ca avait pour effet de lancer X combats d'un coup et le client n'arrivait plus à suivre.
Le commit date un peu...

**Comment by 5pilow** [comment]
Je suis pas sur, j'arrive parfois à reproduire le problème, j'ai testé un peu mais j'ai pas trouvé de fix facile :/

**Comment by 5pilow** [comment]
Ça devrait être mieux maintenant
