### ISSUE TITLE
En cas de déconnexion, le websocket ne se reconnecte pas automatiquement

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#140]
Bonne chance pour débogguer ça

**Comment by Becold** [comment]
![image](https://cloud.githubusercontent.com/assets/12863317/21596281/81f6dd98-d139-11e6-8d70-7e1561aa863b.png)

**Comment by Becold** [comment]
Afficher une erreur en disant que la connexion a laché

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/98672c79f38d85db4b59bc32607f8346a1ac9c4d
+
https://github.com/leek-wars/leek-wars-client/commit/932acbca81243eed670fa8d7dc9028f4ef4d97ae
