### ISSUE TITLE
Colorisation des notifications

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#141]
Vert pour victoire etc.
Option

**Comment by Becold** [comment]
Peut-être rendre ça optionnel
(parce que certaines personnes n'aiment pas avoir une page de notification aux couleurs de l'arc-en-ciel)

**Comment by 5pilow** [comment]
J'ai marqué "Option" :p

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/935ae2afb035a5229be42f4b3763035be6ba53ef
