### ISSUE TITLE
Afficher les dossiers des IA dans la liste déroulante de la popup de test

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#143]
![img](http://image.prntscr.com/image/e8c9b30a7fcb4d2c8198b55e972b3038.png)

**Comment by jeuxjeux20** [comment]
~~La v3 alors ? ;)~~

**Comment by Becold** [comment]
Avec la refonte des tests sur l'éditeur, ce bug n'existe plus.
Dernier commit à ce jour : 696b3e5
