### ISSUE TITLE
[Traduction] Noms de trophées dans les notifications

### ISSUE THREAD

**Issue by Poonex32** [leek-wars/leek-wars-client#156]
Lors de l'acquisition d'un trophée, le nom de celui-ci est systématiquement en anglais dans la liste des notifications.

![screenshot](https://cloud.githubusercontent.com/assets/24856313/22596378/9cd7b8fc-ea2b-11e6-97c2-68d01ec77120.png)

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/168019343d3d960e2ab058bdc0457375af9fec05
