### ISSUE TITLE
[Test] Les poireaux peuvent avoir plusieurs mêmes puces

### ISSUE THREAD

**Issue by jeuxjeux20** [leek-wars/leek-wars-client#159]
![image](https://cloud.githubusercontent.com/assets/16415180/22621352/ee214894-eb21-11e6-8352-0668390ab362.png)

**Comment by Becold** [comment]
Fixé, non ?

**Comment by PerthuisQuentin** [comment]
Pas sur les poireaux de test, non.

**Comment by 5pilow** [comment]
Je n'avais pas vu mais cette issue est corrigé depuis la maj 2.01
