### ISSUE TITLE
[Doc] Phrase manquante

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#160]
![image](https://cloud.githubusercontent.com/assets/16955502/22867179/19ac5604-f183-11e6-986e-dfedb5bd8496.png)

Le texte devrait être : "Stocke la valeur value dans le registre de clé key. La clé et la valeur sont des chaînes qui doivent contenir respectivement 100 et 5000 caractères au maximum. Un poireau peut posséder au maximum 100 registres, le stockage dans un nouveau registre ne fonctionnera pas si tous les registres sont déjà occupés."

La dernière phrase et présente dans les datas, mais pas affichée.

**Comment by 5pilow** [comment]
J'ai corrigé pas mal de trucs comme ça dans 38f671fa2d54b9ca501ec59930044e085be71175, 2cde75b7dad78b33e20d68db19a05da43aad1301 et 2ece4136dde2c1198c66ff15044448b91c046b3e
