### ISSUE TITLE
[Messages privés] Problème d'affichage au premier message

### ISSUE THREAD

**Issue by Onepierre** [leek-wars/leek-wars-client#166]
Il semble y avoir un petit problème lorsque l'on veut envoyer un MP à quelqu'un pour la première fois. Sa photo de profil est affichée trop grande.

![bug1](https://cloud.githubusercontent.com/assets/26046615/23343490/8c8b11a8-fc6c-11e6-8826-8c365ab9c345.PNG)

**Comment by 5pilow** [comment]
4cb4378cb4c0f10825f368651c3f140b4fd8ef9b
