### ISSUE TITLE
[Leek] Tooltips des popup d'équipement bugé

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#170]
Ça concerne toutes les popus de la page des poireaux. Equipements d'armes, puces, chapeaux, IA.

Si on ouvre une de ces popus, les tooltips sont présent.
Ensuite, en allant sur une autre page, comme le Potager par exemple, puis en revenant sur la page, puis sur la popup. Les tooltips n'apparaissent plus.

**Comment by Becold** [comment]
Je pense que c'est parce que la div #popups n'est pas vidée correctement.
![image](https://cloud.githubusercontent.com/assets/12863317/23664621/5a812436-0356-11e7-8139-a63b2f13c917.png)

Solution 1:
Ca ne supprime pas les div mais ça les display:none; seulement. Il faudrait essayer de les supprimer du DOM. [Sur cette ligne](https://github.com/leek-wars/leek-wars-client/blob/814cbfaf6abd38cfe518323efb9550b00da83b7d/http/script/_.js#L631), un .hide() ne suffit pas.

Solution 2:
Lorsque l'on appelle [.show](https://github.com/leek-wars/leek-wars-client/blob/814cbfaf6abd38cfe518323efb9550b00da83b7d/http/script/_.js#L547), vérifier si la div n'existe pas déjà. Si oui, faire un .appear de cette div (et ne pas la regénérer comme on le fait en ce moment).

Je n'ai pas trop le temps de fix ça en ce moment... Désolé. Mais je suis casiment sur que le problème vient de là.

**Comment by LoicDoitteau** [comment]
#174 Je supprime les popups existantes au chargement de la page leek
