### ISSUE TITLE
Changer l'apparence d'un poireau ne le change pas sur son profil

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#182]
Si on change l'apparence d'un poireau et que l'on se rend sur https://leekwars.com/farmer, le poireau n'a pas changé. Il faut rafraîchir la page.

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/357c974d9a0eba193f260e651eff9c74a8554898

**Comment by Becold** [comment]
Les potions changent bien le skin du poireau, mais il y a aussi le chapeau à changer.

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/issues/252
