### ISSUE TITLE
[Trophées] Invocateur : compteur à 1/1

### ISSUE THREAD

**Issue by Zilliq11** [leek-wars/leek-wars-client#185]
Pour le trophée invocateur, le compteur est à 1/1 au lieu de 18/100 dans mon cas.

Du coup la jauge est remplie alors qu'elle ne devrait pas.
Le trophée n'est pas débloqué pour autant.

=> il faut juste modifier le compteur et tout devrait rentrer dans l'ordre.

![image](https://cloud.githubusercontent.com/assets/9016031/23937643/d4c6237e-0958-11e7-8363-b744d54ee292.png)

**Comment by PerthuisQuentin** [comment]
Je pense que c'est coté serveur.
Au niveau de l'API **get-farmer-trophies** : 
Pour le trophée **Entraineur**, le **threshold** est bien de 1000.
Par contre, sur **Invocateur**, le **treshold** est à 1.

**Comment by 5pilow** [comment]
Fixé, merci ;)
