### ISSUE TITLE
Bug d'affichage nom compo dans le garden

### ISSUE THREAD

**Issue by Ebatsin** [leek-wars/leek-wars-client#187]
Lorsque le nom d'une compo contient une apostrophe, l'apostrophe ainsi que tous les caractères suivants ne sont pas affichés dans le garden (pour l'affichage "`nomDeLaCompo` contre :")

**Comment by 5pilow** [comment]
Fixed https://github.com/leek-wars/leek-wars-client/commit/57235540d2e2f122c53c001efd625b2852c4ecf8
