### ISSUE TITLE
[Leek] Bug lors de multiples changement d'armes / puces

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#188]
On ne peut pas faire plusieurs changements d'équipement dans la popup. Certains changements ne sont pas pris en compte.

https://github.com/leek-wars/leek-wars-client/blob/master/http/script/leek.js#L813

L'API retourne le nouvel item ID, mais il n'est pas pris en compte. Du coup, les item ID dans la popup restent les mêmes. Généralement, le premier changement est pris en compte, mais pas les suivants. Il faut recharger pour avoir les nouveaux item ID.

TL;DR
Exemple : 
J'ouvre la popup d'équipement d'arme. J'équipe un pistolet, puis je le déséquipe. Si ensuite je recharge la page, il est toujours équipé.

![2017-03-16_15-50-29](https://cloud.githubusercontent.com/assets/16955502/24002193/62d02c48-0a60-11e7-9f69-69a6ebaa6420.gif)

**Comment by Becold** [comment]
Il faudrait (que sur l'API), il y ait des routes qui ne prenne pas en compte l'id d'un item mais l'id du template.

**Comment by PerthuisQuentin** [comment]
Fixé sur la PR #192  :D
