### ISSUE TITLE
[trophées] Chasseur séparé de Pacificateur + pas de compteur

### ISSUE THREAD

**Issue by Zilliq11** [leek-wars/leek-wars-client#194]
![image](https://cloud.githubusercontent.com/assets/9016031/24198584/be828734-0f06-11e7-8441-546fc2afd6fe.png)

**Comment by 5pilow** [comment]
Fixed with https://github.com/leek-wars/leek-wars-client/commit/8b51a631ab322b217ba8dd42db696133bc31ca70
