### ISSUE TITLE
Hud "connecté" sans être connecté

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#207]
En allant pour la premiere fois sur leekwars aujourd'hui, j'étais sur l'accueil non-connecté et j'avais[ l'hud d'un user connecté mais tout était vide](https://puu.sh/uZAmP/ee4aaf127b.jpg).

Je pense que mes cookies ou mon token était périmé pcq je me connecte de temps en temps depuis mon téléphone. Du coup pour résumé, je n'avais ni cookies/token mais en localstorage j'étais considéré comme connecté.

Reproduction du bug: Changer le cookie "token" par quelque chose de random

Causé par c805a60ea12578317d2c5f678e39345d71c38240

Il faut améliorer la condition présente dans le commit c805a60ea12578317d2c5f678e39345d71c38240

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/b65f0cbfd428d61289ae12a719ae0df11eb64bae
