### ISSUE TITLE
[Edge] Bruit parasite au lancement d'un fight

### ISSUE THREAD

**Issue by Ebatsin** [leek-wars/leek-wars-client#219]
Lorsque l'ont joue un son depuis une source externe à Edge (ça peut être un player audio, une vidéo Youtube, etc.), lorsque l'on lance un fight avec le son des effets activés, au tout début du fight, ça crée un bruit parasite pendant 3-4 secondes.

ça ne le fait que sur Edge. 

C'est à reproduire par quelqu'un d'autre pour confirmer le bug parce que mon setup audio est assez spécial et peut créer des effets bizarres dans certains cas.

**Comment by PerthuisQuentin** [comment]
Avec une vidéo lancée sur Chrome, je viens de lancer un fight sur Edge, j'ai rien entendu de particulier.

**Comment by Becold** [comment]
Je n'ai pas réussi à reproduire le bug.

**Comment by Ebatsin** [comment]
Ça a l'air d'être lié à mon setup du coup. Je ferme.
