### ISSUE TITLE
Changement du fonctionnement du classement par équipe

### ISSUE THREAD

**Issue by ClockerZ** [leek-wars/leek-wars-client#231]
Le classement par equipe est determiné par la moyenne des classement en talents des compositions, ce qui pose un problème : les compositions de classements plus faibles tirent l'equipe vers le bas.
En effet il est rentable pour les equipes de se débarasser des compositions classées plus faibles afin de faire monter le niveau moyen de l'equipe, qui ne sera qu'au final la valeur de talent de la meilleure composition de l'equipe. 
Selon moi, cela va à l'encontre des idées de game design véhiculées par le fonctionnement des equipes.

Pour remédier à cela, je propose plusieurs autres facons de calculer le classement en talent d'une equipe (classées par ordre décroissant en interêt selon moi) :
1. Talent de l'equipe = talent maximal parmis les différentes compositions
2. Talent de l'equipe = somme des talents supplémentaires à 1000 des talents des compositions
3. Talent de l'equipe = somme des talents des compositions (même que la 2. mais pousse aux multiplications inutiles des compositions)

La 2. et la 3.  s'opposent à la 1. en pousant les joueurs à créer plus de compositions mais est moins juste compétitivement (des equipes seraient pénalisées pour n'avoir que peu de poireaux disponibles).

ou encore changer le fonctionnement de la page des classements pour faire un classement par compositions et non par equipes.

ClockerZ

**Comment by 5pilow** [comment]
J'ai opté pour la solution 1 : le talent d'une équipe est le talent de sa meilleure compo. Effectivement l'ancien système était pas très efficace, merci pour la suggestion :)
