### ISSUE TITLE
[idée][forum] Mettre en avant le(s) message(s) avec le plus d'avis positif

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#233]
~~Lorsqu'un message reçoit beaucoup trop d'avis négatif (c'est à dire qu'il ne répond pas vraiment au topic ou est hors sujet), le message pourrait devenir légèrement transparent pour indiquer à l'utilisateur que le message ne répond pas au topic.~~

**Comment by Becold** [comment]
Ou l'idée inverse serait de mettre en avant les messages noté positivement

**Comment by LoicDoitteau** [comment]
Je serais plutôt pour mettre un message positif en avant.
L'autre proposition se rapproche trop de la censure d'après moi, même si ça se fait déjà sur v=beaucoup de sites.

**Comment by 5pilow** [comment]
Je ne prévois pas de faire ça, je préfère garder l'ordre normal du forum :)
