### ISSUE TITLE
[MP] Conversation qui remonte

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#236]
Chez moi, j'ai toujours le problème de la conversation qui remonte à la réception ou à l'envoi d'un message.
A force, c'est vraiment trèèès chiant dans les longues conversations.

**Comment by Becold** [comment]
Sous quel navigateur ? Je n'ai pas de problème sous chrome.
Ou alors on ne parle pas du même comportement.

**Comment by PerthuisQuentin** [comment]
Chrome.

![2017-04-26_18-29-01](https://cloud.githubusercontent.com/assets/16955502/25445332/64c6892a-2aae-11e7-8806-396f5c896c76.gif)

**Comment by 5pilow** [comment]
Si c'est le userscript tu es déchu du grade de modérateur :heart:

**Comment by PerthuisQuentin** [comment]
Raaah, c'était bien le fichu userscript de design du chat.

Plus de PRs pour virer tout les userscripts, viteuh !

Mon mauvais :D
