### ISSUE TITLE
Afficher la date complète des dates sur les chats

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#239]

**Comment by LoicDoitteau** [comment]
La date doit normalement s'afficher au survol de l'heure d'envoi du message, mais la traduction est cherchée dans le fichier de traduction du forum au lieu de celui du main. [main.js](https://github.com/leek-wars/leek-wars-client/blob/master/http/script/main.js#L3872) [main.lang](https://github.com/leek-wars/leek-wars-client/blob/master/http/lang/fr/main.lang#L8)

**Comment by PerthuisQuentin** [comment]
Sinon, plutot que d'afficher au survol.
Il pourrait y avoir une démarcation entre deux messages ayant une date différente.

Exemple : 
![image](https://cloud.githubusercontent.com/assets/16955502/25631657/56663de0-2f71-11e7-918c-afcf1d16e698.png)
Je parle pas du "Aujourd'hui à XX:XX" dans les messages.
Mais du "2 Mai 2017" au milieu.

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/2f87dd1e8508d737e395a8c6113082ce8825e856
