### ISSUE TITLE
Survol des barres d'xp cassé sur la page des reports

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#242]
En combat d'équipe, les barres des poireaux d'une équipe ont les mêmes valeurs d'xp

**Comment by 5pilow** [comment]
Je n'ai pas le problème de mon côté, un screenshot pour illustrer ?

**Comment by Becold** [comment]
Sur le combat https://leekwars.com/report/21355945
Dans mon équipe : 
![image](https://cloud.githubusercontent.com/assets/12863317/25660628/6c59efce-300d-11e7-8c6a-bad6baa41fd3.png)
![image](https://cloud.githubusercontent.com/assets/12863317/25660634/723f2288-300d-11e7-904a-a81aa252a704.png)
![image](https://cloud.githubusercontent.com/assets/12863317/25660650/7d495ec8-300d-11e7-8202-28bc22a2bc62.png)
![image](https://cloud.githubusercontent.com/assets/12863317/25660656/87054b16-300d-11e7-9212-a451c99b7e34.png)

On dirait qu'il n'ajoute pas l'xp du niveau en cours

**Comment by Ebatsin** [comment]
En fait ce n'est pas lié aux combats d'équipe. Ça arrive dans tous les types de combats. Seul l'xp du niveau est affichée. ça n'ajoute pas l'xp.

Et l'xp gagnée pendant le combat est floorée après son passage en pourcentage pour l'affichage de la barre verte. le fait que ce soir floor fait que ce n'est pas toujours affiché même si ça aurait été visible à l'écran.

**Comment by Becold** [comment]
C'est corrigé.
