### ISSUE TITLE
Recevoir une notification lorsqu'un BR est lancé

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#245]
Sur https://leekwars.com/notifications

**Comment by 5pilow** [comment]
Mais pourquoi faire ?

**Comment by Becold** [comment]
Pour garder une trace du BR quelque part pendant quelques jours

**Comment by 5pilow** [comment]
Ah ouais bon argument :p

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/4f293787157bd1338f3983637a94878c6cb44a13
