### ISSUE TITLE
Erreur JS sur la page d'une équipe

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#246]
Lorsque l'on est déconnecté et que l'on va sur [une page d'équipe](https://leekwars.com/team/1), on reçoit cette erreur dans la console : 
![image](https://cloud.githubusercontent.com/assets/12863317/25717912/61c79c12-3104-11e7-961e-c07c5253d96d.png)

Elle n'affecte en rien la navigation du site mais quelque chose ne me semble pas clair.

**Comment by 5pilow** [comment]
J'arrive pas à reproduire :/

**Comment by Becold** [comment]
1. Incognito mode sur chrome
2. F12
3. https://leekwars.com/team/1765
4. [L'erreur ](https://cloud.githubusercontent.com/assets/12863317/25728559/2d7d559c-3130-11e7-8023-88a4b2096adc.png) pointe vers cette ligne : 
![image](https://cloud.githubusercontent.com/assets/12863317/25728535/0f1a25bc-3130-11e7-8ef3-eba02ff36201.png)

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/f5b378e1c77ff56e6eeccc241f04ebce9f8cde0b

Merci :+1:
