### ISSUE TITLE
[idée] Icone de poireau devant le(s) poireau(x) en vie dans le report

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#250]
Sur le report https://leekwars.com/report/21416504
fabzze et twogether sont considéré comme des invocations
![image](https://cloud.githubusercontent.com/assets/12863317/25822600/5cd81b9a-3439-11e7-894e-339d654c3a4f.png)

**Comment by Becold** [comment]
Working as intended

**Comment by Shakadak** [comment]
Ca pourrait tout de même être l'objet d'une amelioration visuelle. Quelque chose comme l'icone du site au même niveau que les cranes.

**Comment by 5pilow** [comment]
J'ai légèrement fixé l'alignement des noms : https://github.com/leek-wars/leek-wars-client/commit/520755f873021fd8f8bc38f6b6db737163f168bc
