### ISSUE TITLE
[br] Mauvais résultat affiché sur la page du poireau

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#256]
Sur le combat https://leekwars.com/fight/21514959 , mon poireau **Neissa** a perdu mais pourtant, il est indiqué sur sa page de poireau qu'il a gagné.
![image](https://cloud.githubusercontent.com/assets/12863317/26132521/41f4b716-3aa1-11e7-8796-9eee8a37911d.png)

**Comment by 5pilow** [comment]
C'est bon ;)
