### ISSUE TITLE
[accept condition] Retirer le hard refresh

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#267]
https://github.com/leek-wars/leek-wars-client/blob/9203483f801574fd6a783ddf5fa4f45e6e2f0a1d/http/script/accept_conditions.js#L6

**Comment by 5pilow** [comment]
Cette page n'est plus utilisé de toute façon ^^

**Comment by 5pilow** [comment]
Je ferme du coup ;)
