### ISSUE TITLE
[command ping] Le pong se fait seulement dans le chat où on a écrit

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#270]
![image](https://cloud.githubusercontent.com/assets/12863317/26657041/0f029c3e-4662-11e7-8417-b8e46336e0dc.png)

**Comment by Becold** [comment]
Mmmmh.. Je n'arrive plus à reproduire le bug.

**Comment by 5pilow** [comment]
Yep, c'est corrigé on dirait bien :)
