### ISSUE TITLE
[notification] Les icones "perdant-gagnant" ne sont pas centrées dans la bulle

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#271]
![image](https://cloud.githubusercontent.com/assets/12863317/26657579/ea6814c8-4664-11e7-9219-fff9da456d20.png)

**Comment by Ebatsin** [comment]
Une couleur sur l'intégralité de la notif serait plus facile pour juger les résultats au premier coup d'oeil ou estimer le ratio de win/lose rapidement aussi

**Comment by 5pilow** [comment]
Chez moi :
http://imgur.com/a/tKryA

faut mettre une image du coup ^^

**Comment by Becold** [comment]
Je crois que c'est corrigé de mon côté, j'ai besoin d'une confirmation pour fermer l'issue. :)
