### ISSUE TITLE
[menu] Classement n'est plus selectionnée

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#272]
Sur la page classement: 
![image](https://cloud.githubusercontent.com/assets/12863317/26657752/249a0e48-4666-11e7-9051-3bd27a1e9bbb.png)

Sur la page forum : 
![image](https://cloud.githubusercontent.com/assets/12863317/26657763/2fdba17c-4666-11e7-9298-5e130089e56a.png)

**Comment by 5pilow** [comment]
Fixé

**Comment by 5pilow** [comment]
Nan mais t'es trop rapide xD
