### ISSUE TITLE
[leek] Tooltips des popup d'équipement bugé

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#277]
Retour de #170 à cause de d68cf8828a34a0b07882eacc5b8b3079f5f11576

**Comment by 5pilow** [comment]
Sûr ?

**Comment by Becold** [comment]
Oui, les étapes pour reproduire le bug : 
1. Aller sur la page du poireau 1. Ouvrir le panel de ses puces -> Les tooltips fonctionnent.
2. Sans reload, aller sur la page du poireau 2. Ouvrir le panel de ses puces. -> Les tooltips ne fonctionent plus.

**Comment by 5pilow** [comment]
D'accord merci :) je corrige ça demain !

**Comment by 5pilow** [comment]
Devrait être corrigé avec le passage à Vue
