### ISSUE TITLE
Mise à jour de l'inventaire

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#279]
Problème de mise à jour de l'inventaire, d'un poireau à un autre.

Pour reproduire : 
Aller sur un poireau, lui retirer une puce. Elle apparaît dans l'inventaire.
Aller sur un autre poireau. La puce retirée n’apparaît pas dans l'inventaire.

**Comment by 5pilow** [comment]
C'est maintenant corrigé sur la bêta
