### ISSUE TITLE
[Forum] Topic modération visible dans la recherche

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#281]
Les topics de la catégorie Modération sont visibles dans les résultats de recherche pour tout le monde.

**Comment by Becold** [comment]
Tu as le grade de modérateur, donc tu as accès à ces topics là.
Mais les contributeurs/membres n'y ont pas accès (en tous cas, j'ai pas réussi à reproduire le bug).

**Comment by PerthuisQuentin** [comment]
Sans blague ? :D
HorsSujet a fait le test tout à l'heure, c'est lui qui m'en a parlé.
Il voyait bel et bien un topic modération.

**Comment by Becold** [comment]
![image](https://cloud.githubusercontent.com/assets/12863317/26755477/4c9af0c2-488e-11e7-9d09-68e9bf36fb4e.png)

Rien non plus sur les autres pages. Donc seuls les membres seraient affectés ?

**Comment by GuimDev** [comment]
Je soutiens @PerthuisQuentin. Cependant il y a dû avoir une modification entre temps.

Ça serait bien de ne pas-être agressif.

**Comment by GuimDev** [comment]
Je n'y ai plus accès alors que je le voyais hier.

@Becold: Tes comptes ont-ils une Team ?

**Comment by Becold** [comment]
Mes comptes qui n'ont pas d'équipe arrivent à voir le topic.
Mes comptes qui ont une équipe n'arrivent pas à le voir.

Bien vu @GuimDev :)

**Comment by PerthuisQuentin** [comment]
Logique.

:D

**Comment by 5pilow** [comment]
C'est corrigé, en plus de nombreux autres bugs sur la recherche forum :)
