### ISSUE TITLE
[regex url] Ajouter un $ à la fin d'un lien

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#290]
`http://www.google.com/$`
produit
![image](https://user-images.githubusercontent.com/12863317/26882514-ea0e31de-4b9a-11e7-9501-1245584acfc9.png)

Il faut que l'url termine par / pour reproduire le bug.

**Comment by Becold** [comment]
42d54fa9bf7ad315c98f81eda527854c158fcadd

**Comment by 5pilow** [comment]
Ah cool x)

**Comment by Becold** [comment]
Oups, c'était #257 que je voulais fermé. Cette issue ici reste toujours d’actualité!
Désolé.

**Comment by 5pilow** [comment]
Bon j'ai corrigé en interdisant les dollars dans les URLs, donc ça arrête le lien au premier dollar trouvé

**Comment by 5pilow** [comment]
En fait j'ai préféré remplacer les dollars par %24, comme ça ça fonctionne si jamais ^^
