### ISSUE TITLE
[sibebar mp] Parler à quelqu'un qui n'est pas dans le panel de droite n'affiche ni son pseudo ni son avatar

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#291]
![image](https://user-images.githubusercontent.com/12863317/26882749-863686e2-4b9b-11e7-9775-6557f009ce07.png)

Reproduction du bug : 
Parler à quelqu'un qui se trouve déjà dans /messages (dans la colonne à gauche) mais pas dans le panel "messages" à droite.

**Comment by 5pilow** [comment]
Ce bug n'existe plus dans la bêta (même si y'en a d'autres :p)
