### ISSUE TITLE
[change password] Déconnecter l'utilisateur lors d'un changement réussi de password

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#292]

**Comment by GuimDev** [comment]
Pourquoi ?

**Comment by Becold** [comment]
Oui, pour forcer le changement du token.

Pour moi, un changement de pass est soit dans l'optique de prêter le compte à quelqu'un d'autre, soit que l'utilisateur sent que quelque chose est anormal. Le déconnecter le forcera à regénérer le token. :)

**Comment by 5pilow** [comment]
Je pense que c'est une bonne idée de supprimer le token oui

**Comment by GuimDev** [comment]
Et un bouton "déconnexion des autres sessions" ?

**Comment by 5pilow** [comment]
C'est fait, le changement de mot de passe invalidera les tokens actuels et donc déconnectera toutes les sessions de l'éleveur.
