### ISSUE TITLE
[tournois] inverser l'effet du bouton d'inscription

### ISSUE THREAD

**Issue by Liemmerle** [leek-wars/leek-wars-client#304]
Inscrire les poireaux (et éleveurs) par défaut, et devoir appuyer sur le bouton pour se désinscrire permettrai certainement de réduire les problèmes d'écart de niveaux trop grands en tournoi.

En plus, ça rendra inutile le script inscrivant automatiquement les gens en tournoi.

**Comment by Becold** [comment]
J'aime bien l'idee mais du coup le générateur de tournoi doit générer beaucoup trop de combats.

À creuser.

**Comment by 5pilow** [comment]
Oui je préfère le comportement actuel.
