### ISSUE TITLE
[message] Aléatoirement, certains messages envoyés vont tout en haut de la liste des messages

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#308]
Reproduction du bug : 
(à reproduire chaque jour, donc à minuit)
1. La personne A envoit un message à la personne B. Un séparateur de "nouveau jour" se crée.
![image](https://user-images.githubusercontent.com/12863317/27260722-bb6bcd40-5433-11e7-9baf-434d639cce7b.png)
2. La personne B répond au jour J. Le message va tout en haut de la liste des messages. Si la personne B continue d'envoyer des messages, ses messages iront tout en haut.
3. Si on rafraîchit la page, les messages vont au bon endroit. Etant donné que la personne B voit ses messages au bon endroit, ses messages envoyés iront en dessous.

Résumé:
Si la personne A envoit un message à 0h01 (ce qui crée un nouveau sépareteur) et que la personne B lui réponds à 16h, le bug se produit. A reproduire chaque jour.

**Comment by Becold** [comment]
La reproduction du bug est efficace à 100%. Mais j'ai trouvé un autre cas où ça arrive aussi.

**Comment by 5pilow** [comment]
Corrigé, la date du serveur était mise en cache en même temps que le head, à cause du service worker.
Pour l'instant je disable la mise en cache de la page / qui n'est pas bien utile ^^
