### ISSUE TITLE
[gulp?] Dossier assets et minify les fichiers js/css

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#309]
Ayant en ce moment une connexion plus que désagréable (~160ko/s en download max), je trouve certaines parties du site mal optimisé. Certaines images apparaissent parfois dans sa taille d'origine avant d'être rétréci, par exemple : 
https://leekwars.com/static/image/website.png
https://leekwars.com/static/image/gearing_small_white.png

Ce serait sympa d'avoir un système qui minimify les js/css et rétrécis certaines images à la bonne taille avant chaque mise en prod. L'idée est à creuser.

**Comment by 5pilow** [comment]
Pour les images c'est vrai que certaines sont trop grosses (celle du site web notamment).
Pour le JS/CSS j'ai envie de tenter ça oui, pour charger le site sur mobile peut être intéressant
