### ISSUE TITLE
Blocs de code trop petits sur le forum mobile

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#310]

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/b3191c28ff8e1bb335a9443d8e8415339aeaf3fa

**Comment by Traual** [comment]
Pillow que ce passes-t-il sur Leekwars en ce moment ?

**Comment by 5pilow** [comment]
Petit souci technique, corrigé maintenant
