### ISSUE TITLE
[Paramètres] Changer le texte

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#311]
![image](https://user-images.githubusercontent.com/16955502/27601633-454cc242-5b70-11e7-8cf7-53b9d6e8bf96.png)

Du coup, vu qu'il y a deux options, ce serait bien de changer les "Mail lorsque ..." en "Lorsque ..."

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/8845cc85bf0ab5a1977c014438248b007cd6986d
