### ISSUE TITLE
[Forum] Impossible de supprimer un topic

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#327]
La suppression d'un topic via le bouton supprimer du premier message ne fonctionne pas, à moins d'être modo.

J'ai jeté un œil, mais j'ai pas vu de soucis au niveau du client.
La requête se fait correctement, mais il n'y as aucune info en retour, même pas d'erreur.

Du coup, je suppose que le problème est en back. ¯\\_(ツ)_/¯

**Comment by 5pilow** [comment]
J'ai supprimé le bouton pour les non-modérateurs ;) Je ne souhaite pas que les gens suppriment leur topics, car ça supprime tous les messages, pas cool :/
