### ISSUE TITLE
[Chat] Bug qui fait que la scroll du chat ne reste pas en bas

### ISSUE THREAD

**Issue by GuimDev** [leek-wars/leek-wars-client#339]
Bonjour,

Je souhaite corriger, le bug qui fait que la scroll du chat qui ne reste pas juste en bas du chat au chargement de la page.

Piste de correction : 
 - Ajouter une propriété sur la hauteur des images.
 - Ou en javascript ajouter une vérification dans : `$(window).load();`

**Comment by PerthuisQuentin** [comment]
Est-ce que tu peux préciser un peu dans quel contexte ? Et sur quel navigateur ?

J'ai beau naviguer sur le site, le sidechat, le chat du forum et la page du chat restent bien en bas. Et même au chargement. (Sur chrome)

**Comment by GuimDev** [comment]
Firefox, le mini chat à droite. Quand la page se charge, la scroll n'est pas tout a fait en bas.

**Comment by PerthuisQuentin** [comment]
Okay, effectivement, pour moi aussi, sur firefox.

Et même, pour être précis, j'ai l'impression qu'il est bien tout en bas, puis il remonte un peu.

**Comment by GuimDev** [comment]
Oui sûrement à cause des images qui se charge après.

**Comment by 5pilow** [comment]
Ça devrait être bon sur la bêta maintenant, je détecte bien une action de scroll de l'utilisateur (souris ou doigt), et annule les scrolls automatiques dans ce cas.
