### ISSUE TITLE
[BUG] Corriger le raccourci du navigateur BACKSPACE

### ISSUE THREAD

**Issue by GuimDev** [leek-wars/leek-wars-client#345]
Bonjour,

La touche BACKSPACE devrait permettre de retourner à la page précédente, il s'agit d'un raccourci du navigateur.

Il faudrait virer le `return false;` ou `e.preventDefault();` dans le trigger keypress.

Similaire à : #275

**Comment by 5pilow** [comment]
Mmh chez moi cette touche ne fonctionne ni sur Firefox ni sur Chromium, et je n'ai pas de `return false;` ou `preventDefault()` sur un event de key global, donc je ne vois pas quoi corriger. Tu aurais des précisions ?
