### ISSUE TITLE
[beta] Confirmation d'achat : balises apparentes

### ISSUE THREAD

**Issue by Si3gward** [leek-wars/leek-wars-client#354]
![screenshot](https://user-images.githubusercontent.com/44274273/47178161-a5daf200-d31a-11e8-9479-802422177b91.png)

Difficile de passer à côté, mais comme ce n'est pas dans la liste du "pas fini", je me permets "au cas où".

**Comment by 5pilow** [comment]
C'est corrigé dans 01274fbddfd5a14ebba2e7574030e15277dc6187, merci :+1:
