### ISSUE TITLE
beta - Page des trophées - barre de progression générale absente

### ISSUE THREAD

**Issue by Kavaliov2** [leek-wars/leek-wars-client#358]
Dans la page des trophées https://beta.leekwars.com/trophies la barre de progression globale tout en haut ne s'affiche pas.
Navigateur Chrome, version à jour.

**Comment by 5pilow** [comment]
Merci à toi ! :+1: 
C'est corrigé dans ab5847f, je ferme quand je le pousse sur le site beta.
