### ISSUE TITLE
beta - Console Leekscript v2 cassée

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#360]
Lorsque j'ouvre la console LS v2, je ne vois que le titre de la popup mais pas la console elle-même.

**Comment by Naheulf** [comment]
Je confirme que l'affichage de la console est buggé (mauvais div ?)
![image](https://user-images.githubusercontent.com/14990967/47179654-e50b4200-d31e-11e8-8355-ad9229efd4fd.png)
