### ISSUE TITLE
beta - Potager par équipe - chargement infini

### ISSUE THREAD

**Issue by Kavaliov2** [leek-wars/leek-wars-client#361]
Quand on a plus de combat d'équipe dispo.
Au lieu d'afficher, l'icone "plus de combat", une animation de chargement s'affiche en continu.

**Comment by Naheulf** [comment]
J'allais ouvrir une issue similaire pous les combats solo/d'éleveur. Le bug est également présent pour le combats BR lorsqu'on a plus de combats de dispo.

**Comment by LoicDoitteau** [comment]
L'url est mal formatée lorque l'on va dans le potager, ex : https://beta.leekwars.com/garden/challenge/undefined/NaN/47183

**Comment by 5pilow** [comment]
La première partie de cette issue devrait être résolue avec ce commit qui corrige toutes les erreurs du potager ;)

**Comment by 5pilow** [comment]
Et ces deux-là sont pour les deux commentaires : BR et état cassé après un challenge
