### ISSUE TITLE
[Beta][Garden] Le clic sur un poireau/éleveur/équipe n'a pas d'effet

### ISSUE THREAD

**Issue by LoicDoitteau** [leek-wars/leek-wars-client#394]

**Comment by 5pilow** [comment]
Une petite erreur JS pour me mettre sur la voie ? :)

**Comment by Becold** [comment]
Pas d'erreur JS de mon côté... 😞

**Comment by 5pilow** [comment]
Oui je pense que c'est la bêta qui bloque le lancement a cause des cookies / session, comme je suis admin j'ai pas la limitation :D

**Comment by Becold** [comment]
Je confirme, on a une requête qui part mais avec un retour `{success: false}`
