### ISSUE TITLE
[Beta][Market] Message dans le cas où rien n'est sélectionné

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#403]
Sur le market, si on arrive à faire en sorte qu'aucun item ne soit sélectionné, on voit le loader charger en boucle. Ce serait pas mal de mettre un message "Aucun objet sélectionné."

https://github.com/leek-wars/leek-wars-client/blob/master/src/component/market/market.vue#L100

**Comment by 5pilow** [comment]
Mmh comment tu arrives à n'avoir aucun item sélectionné ? Par défaut ça prend le pistolet
