### ISSUE TITLE
[API] Incohérence dans la déclaration des paramètres

### ISSUE THREAD

**Issue by Naheulf** [leek-wars/leek-wars-client#409]
La fonction get-all du module services renvoie une incohérence pour la déclaration de ses propres paramètres.
``` 
{
		'id': 26,
		'module': 'service',
		'function': 'get-all',
		'parameters': ['token'],
		'parameters_types': ['string', 'string'],
		'returns': ['services'], 
		'method': 'get'
}
```
Pourquoi est-ce qu'il y a deux valeurs pour `parameters_types` alors qu'il n'y a qu'une valeur pour `parameters` ?

**Comment by 5pilow** [comment]
C'est corrigé merci
