### ISSUE TITLE
[Report] Graphique d'évolution des points de vie non intéractif

### ISSUE THREAD

**Issue by LoicDoitteau** [leek-wars/leek-wars-client#449]
Passer sa souis sur une courbe n'affiche plus le nom du poireau ni ne met la courbe en surbrillance

**Comment by 5pilow** [comment]
Ça fonctionne chez moi, est-ce que c'est aléatoire chez toi ou bien ça ne marche jamais ?

**Comment by 5pilow** [comment]
Voilà je pense que j'ai fixé, sur des grosses pages report, le graphique était pas encore généré après 500ms. Maintenant ça attend bien la fin
