### ISSUE TITLE
[UX] tooltips sur les liens éleveurs/leeks

### ISSUE THREAD

**Issue by tagadanar** [leek-wars/leek-wars-client#454]
Un mouseover sur chaque lien vers une page éleveur, un leek, ou un match permet d'afficher une tooltip contenant toutes les informations pertinentes : 

[exemple d'un leek](https://imgur.com/NkBXfO3)
[et d'un éleveur](https://imgur.com/gSdYW0X)

il y avait aussi un tooltips pour les liens vers les match qui permettait de voir un résumé du match (durée, vainqueur, lien direct vers le report, etc... on pourrait même ajouté les courbes si t'es chaud)

bisous !

**Comment by 5pilow** [comment]
C'est fini pour les tooltips leek/farmer, je vais faire celles de team/fight dans la foulée
