### ISSUE TITLE
[MPs] Pas d'historique de la conv'

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#457]
Si  on charge la page d'une conv' privé directement, l'historique est chargé.
Mais pas si l'on est sur une page puisque que l'on clique sur une conv' dans le panel de droite.

Edit : Bon, c'est pas systématique. La plupart du temps, j'ai l'histo. :/

**Comment by 5pilow** [comment]
Ça devrait être bon ;)
