### ISSUE TITLE
[report] Erreur javascript si le combat n'a pas encore été généré

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#468]
```
Uncaught (in promise) TypeError: Cannot read property 'actions' of null
    at n.a.get.then.t (chunk-common.c2990d3c.js:1)
```

**Comment by 5pilow** [comment]
Est-ce que tu arrives à avoir cette erreur facilement ? Normalement si tu attends quelques secondes dans la console il va charger le fichier .map et te donner le nom du fichier réel ainsi que le numéro de ligne ;)

**Comment by Becold** [comment]
Tu génères une file d'attente (en lançant 3-4 combats assez rapidement), puis tu en lances un nouveau combat (qui sera en file d'attente) et tu appuies sur Q pour aller rapidement sur le rapport.
Sauf que le combat n'étant pas encore généré mais en file d'attente, il affiche cette erreur.

![image](https://user-images.githubusercontent.com/12863317/48676609-53833000-eb69-11e8-8dc2-615fe19cc094.png)

(Je n'ai pas réussi à trouver la ligne)

**Comment by 5pilow** [comment]
Merci pour les précisions, c'est fait !
