### ISSUE TITLE
[Forum] Liens qui sortent de nul part

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#476]
Sur ce topic : https://leekwars.com/forum/category-4/topic-9305/page-1

Lorsque j'écris une réponse, à chaque fois que je saisis un caractère, ça fait apparaître un lien dans le message d'Oimat.
![image](https://user-images.githubusercontent.com/16955502/48952550-e265c300-ef42-11e8-8a8e-7c1eafb50164.png)

**Comment by 5pilow** [comment]
C'est corrigé normalement, avec le changement dans le traitement des emojis
