### ISSUE TITLE
[combat test] Debug capricieux

### ISSUE THREAD

**Issue by Bulbille** [leek-wars/leek-wars-client#482]
1/ faire un poireau personnalisé pour un combat de test
2/ lui donner l'IA : 
`debug("Coucou");`
3/ Lancer le combat avec le poireau personnalisé de test
4/ les debugs ne s'affichent ni en combat ni en log

Suite à une discussion avec Tintin : je précise que ce poireau est dans mon équipe, donc avant la clause "VS".

**Comment by 5pilow** [comment]
C'est également corrigé !
