### ISSUE TITLE
[combat test] Pause 

### ISSUE THREAD

**Issue by Bulbille** [leek-wars/leek-wars-client#483]
1/ faire un poireau personnalisé pour un combat de test
2/ lui donner l'IA :
`pause();`
3/ Lancer le combat avec le poireau personnalisé de test
4/ aucune pause ne s'effectue durant le combat de test

Suite à une discussion avec Tintin : je précise que ce poireau est dans mon équipe, donc avant la clause "VS".

**Comment by 5pilow** [comment]
C'est corrigé ! merci
