### ISSUE TITLE
[Aide] Information pas a jour (en/fr)

### ISSUE THREAD

**Issue by yaelMagnier** [leek-wars/leek-wars-client#486]
Dans https://leekwars.com/help/general
il y a (de meme en francais)
> Reaching higher levels for your leek will allow you to use more LeekScript functions. Each function is rated with a level which is displayed on the right of the function name in the documentation. These level is the mimimum requested to be allowed to use this specific LeekScript function.

**Comment by 5pilow** [comment]
C'est à jour maintenant ;)
