### ISSUE TITLE
[Langue] le site ne sauvegarde pas la langue dans les settings

### ISSUE THREAD

**Issue by yaelMagnier** [leek-wars/leek-wars-client#493]
Le site change automatiquement de français a anglais après que je modifie les settings de langue d'anglais a français.

**Comment by 5pilow** [comment]
Bonjour, alors personnellement je n'ai pas ce bug, la langue reste bien après un rafraichissement de la page.
Peut-tu me décrire un peu plus la procédure pour reproduire le bug ? Quel navigateur et quelles options (cookies, extensions etc.) utilises-tu ?

**Comment by 5pilow** [comment]
Une personne ayant ce bug sur le forum ne l'a plus maintenant, donc on va dire que c'est corrigé ;)
