### ISSUE TITLE
[Team] Cliquer sur le profil d'un candidta mène à une URL erronée

### ISSUE THREAD

**Issue by LoicDoitteau** [leek-wars/leek-wars-client#498]
![image](https://user-images.githubusercontent.com/17564388/53022733-124a3700-345c-11e9-91c9-9215ed1dff68.png)
https://github.com/leek-wars/leek-wars-client/blob/d92089099a3cd3a6c68221f7156c2f0644a45ed1/src/component/team/team.vue#L117

Je crois qu'il manque les deux points pour binder le js

**Comment by 5pilow** [comment]
Corrigé merci !
