### ISSUE TITLE
Notifications E-mail impossible à désactiver

### ISSUE THREAD

**Issue by bibimission** [leek-wars/leek-wars-client#511]
Alors que j'avais désactivé les notifications E-mail pour les messages suivis du forum, depuis la Maj, j'en reçois à nouveau. Et lorsque que je regarde sur le site, la checkbox est décochée. J'ai essayé de la cocher/décocher à plusieurs reprises mais rien n'y fait.
BougeLeGrosOrteil est aussi dans le même cas. On utilise tous les deux Firefox.

**Comment by 5pilow** [comment]
C'est corrigé !
