### ISSUE TITLE
[Bug] Plus de crânes sur les poireaux morts dans un rapport de combat

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#516]
Il semble ne plus y avoir les crânes indiquant les poireaux morts à la fin d'un combat.

Quelques exemples :
https://leekwars.com/report/29809725
https://leekwars.com/report/29809856
https://leekwars.com/report/29809878

**Comment by 5pilow** [comment]
C'est corrigé merci :)
