### ISSUE TITLE
Mail reçu malgré les préférences

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#519]
Je viens de recevoir un mail me disant qu'il y a eu une réponse sur ce topic : 

Pourtant, mes préférences sont celles-ci :
![image](https://user-images.githubusercontent.com/16955502/68744575-36a30080-05f5-11ea-9c3b-e9b3285c0668.png)

Je ne crois pas avoir reçu de mails sur des réponses à des topics récents. Pour l'instant, il n'y a que ce vieux topic pour lequel j'ai reçu un mail.

**Comment by PerthuisQuentin** [comment]
Oops, duplication de #511

**Comment by 5pilow** [comment]
C'est corrigé !
