### ISSUE TITLE
[Marché] Le son du J-Laser ne se lance pas

### ISSUE THREAD

**Issue by Kaeldazs** [leek-wars/leek-wars-client#526]
**Environnement de test** :

- **LW Version**: 2.08 (16 janvier 2020)
- **Navigateur**: Firefox 72.0.1 (64 bits)
- **OS**: Windows 10
--------------------------------------
**Reproduction de l'anomalie** : 

- Sélection de l'arme **J-Laser** dans le marché
- Clique sur l'image de l'arme dans le cadre "**Caractéristiques**"
    - _Le son de l'arme n'est pas joué_
    - _Affichage d'une erreur dans la console_ : **TypeError: "e is undefined"**
--------------------------------------
**Informations complémentaires** :

- Le son est joué pour toutes les autres armes du marché, seul le J-Laser semble impacté par l'anomalie

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/5550786c57542eb1fc1fe05148b47be72a55564f
