### ISSUE TITLE
Supprimer les console.log d'informations en production

### ISSUE THREAD

**Issue by jonathanjdev** [leek-wars/leek-wars-client#53]
Pourquoi pas supprimer les console.log d'informations, qui sont inutiles en production comme :

```
WS received :  [9, Array[7]]
Post : farmer/update Object {}
Res :  Object {success: true}
```

Et seulement conserver les console.log signalant des erreurs ?

**Comment by 5pilow** [comment]
C'est fait, et ceux en version locale sont plus beaux ;)
