### ISSUE TITLE
Amélioration de l'affichage lors de l'équipement d'armes/puces

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#68]
Amélioration de cette interface d'équipement :
![image](https://cloud.githubusercontent.com/assets/16955502/19771299/c0f04ce8-9c62-11e6-8fcf-fa92ecc1b6bb.png)
- Mêmes armes et puces stackés ? Avec ce genre d'affichage :
  ![image](https://cloud.githubusercontent.com/assets/16955502/19771347/ed1eb8f4-9c62-11e6-8ffd-91df49b687b1.png)
- Un tri autre que par niveau ? Un tri type market sort/autre ?
- Pour les armes. Peut-être leur donner une largeur fixe ? Afin d'avoir un truc un poil plus visuel ?
  ![image](https://cloud.githubusercontent.com/assets/16955502/19771504/672bcdda-9c63-11e6-9ffc-9b8b2f441f28.png)

**Comment by 5pilow** [comment]
Ce sont de très bonnes idées ;) Pour les puces un tri par catégorie peut être bien oui, les armes par niveau ça suffit je pense :)

**Comment by Becold** [comment]
Même chose pour les chapeaux? :)
![image](https://cloud.githubusercontent.com/assets/12863317/20628303/70fa7054-b325-11e6-9e7c-df03c5c54dda.png)

**Comment by Becold** [comment]
Cette idée avait l'air très très sympa. Mais je pense qu'il faudrait une refonte de l'api, c'est compliqué de manipuler les objets en front comme ils sont en ce moment.

**Comment by PerthuisQuentin** [comment]
T'as travaillé sur cette issue ? Si oui, on en parle, j'ai avancé dessus de mon coté, c'est fonctionnel, mais c'est un prototype quoi.

Manipuler dans l'état actuel, ça passe.
Mais c'est certain que ça faciliterais les choses si les items était déjà regroupés.

Là, j'suis obligé de les regrouper. Et en plus de ça, ensuite que je les range par types, un peu comme dans le market sort mais sans séparer les catégories.

![image](https://cloud.githubusercontent.com/assets/16955502/22640843/98856288-ec54-11e6-9aeb-76ecb845690a.png)

**Comment by Becold** [comment]
J'ai tenté quelque chose mais prise de tête.

Bon courage. :)

**Comment by 5pilow** [comment]
Partially done in https://github.com/leek-wars/leek-wars-client/pull/192
