### ISSUE TITLE
Le poison est comptabilisé pour l'entité cible dans le total de dégâts

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars-client#71]

**Comment by Shakadak** [comment]
De ce que j'ai compris du code, l'action correspondante est formée d'un triplet `[action_type, entity_id, value]`. Lorsque un poireau recoit des degats de poison, c'est lors de son propre tour. Dans la manière actuelle de gérer les stats, `LW.pages.report.statistics` se sert de l'entité courante (`currentPlayer`) en tant qu'applicateur de l'action, et `entity_id` en tant que receveur. Et lorsque le poireau recois les dégats, `currentPlayer = entity_id`. A moins de recevoir la source en plus, il n'y a pas vraiment de solution simple, sinon il faut implementer un systeme qui garde trace des effets de poison et de vaccin appliqués.

**Comment by 5pilow** [comment]
C'est exact :)

**Comment by 5pilow** [comment]
Fixed in #229
