### ISSUE TITLE
Mettre à jour les habs dynamiquement

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#77]

**Comment by 5pilow** [comment]
À préciser un peu, où manque-il des actualisations ?
Actuellement les habs sont mis à jour quand :
- Un combat est lancé (gains du combat)
- Lors d'un achat/vente
- Renommage du poireau
- Achat d'un poireau

**Comment by PerthuisQuentin** [comment]
Il y a un cas où les habs ne sont pas actualisés à la réception du combat. 
Pour l'instant, aucune idée du pourquoi.

Par contre, admettons qu'on quitte la page d'attente de la génération du combat. Du coup, les habs ne sont pas actualisés. C'est peut-être un peu dommage ?

**Comment by Becold** [comment]
Je pense que c'est étroitement lié à l'issue #92 et qu'on pourrait faire d'une pierre deux coups.

**Comment by 5pilow** [comment]
Pour le talent c'est différent l'info est même pas envoyée par le serveur ^^

**Comment by 5pilow** [comment]
Fixé côté serveur pour les combats :)
