### ISSUE TITLE
Améliorer la visibilité du chat

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars-client#79]
Encore une personne qui ne s'est rendu compte de l'existence du chat que parce qu'on lui a dit.

Sur les petits écrans, sans le "sidechat", cela passe pas mal inaperçu :/

Pourquoi ne pas rajouter le chat dans le menu de navigation, directement ?
Ou un autre moyen d'améliorer sa visibilité :)

**Comment by jonathanjdev** [comment]
+1

**Comment by 5pilow** [comment]
J'ai réduit légèrement la taille du forum ici : https://github.com/leek-wars/leek-wars-client/commit/2a83cfe44d53adfa14f9fb9b5ce6d8ee19d786cb
