### ISSUE TITLE
Inscrire un poireau dans une BR à partir d'un deuxième onglet

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#82]
1. Dans le premier onglet, inscrire un poireau dans le BR en cours
2. Ouvrir un 2eme onglet, inscrire un autre poireau dans le BR en cours
3. Revenir sur le premier onglet, la petite fenêtre Battle royale ne s'est pas actualisée

**Comment by 5pilow** [comment]
https://github.com/leek-wars/leek-wars-client/commit/bf498d450b6fa5d86d8955dde9d8f223defc1163
