### ISSUE TITLE
La première page du didactitiel n'a pas la bonne hauteur

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#87]
![image](https://cloud.githubusercontent.com/assets/12863317/20814008/40ec31b6-b818-11e6-95d9-ef3ec1740a28.png)
Ps: Quand on passe à la page 2 puis que l'on revient à la page 1, la div a la bonne hauteur

**Comment by 5pilow** [comment]
Fixed in https://github.com/leek-wars/leek-wars-client/commit/9b6428d43dc112d8468e4e5fa0e7121507bda082
