### ISSUE TITLE
"Mot de passe oublié" ne fonctionne pas toujours

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#88]
La feature "Mot de pass oublié ?" envoit bien un email avec un lien au format : 
https://leekwars.com/forgot-password/id_farmer/random_token

Sauf que valider le form ne produit absolument rien du tout.
Et dans la console, on recoit ce retour : 
{"success":false,"error":"error_no_id"}

**Comment by 5pilow** [comment]
Bizarre chez moi ça a marché deux fois de suite. Tu reproduis encore ?

**Comment by Becold** [comment]
J'ai tenté de le reproduire.
1. Je recois l'email, je clique sur le lien
2. Je mets un **nouveau** pass, différent du mien
3. Le formulaire est validé : "Votre mot de pass a bien été modifié"
4. Je suis redirigé vers la connexion, je me reconnecte avec mon nouveau pass
5. "Pass invalide". Je me reconnecte avec mon ancien mot-de-pass
6. Je me log

**Comment by 5pilow** [comment]
Je viens de retester et c'était bon, est-ce qu'on pourrait pas fermer cette issue ?
