### ISSUE TITLE
Dernier mois en dehors du graph des talents

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#93]
![image](https://cloud.githubusercontent.com/assets/12863317/20821753/73c5e604-b845-11e6-9d19-cd5d30a633f9.png)

**Comment by Becold** [comment]
J'ai regardé vite fait. Il est possible d'utiliser l'option "axisX.labelOffset" pour décaler les labels.
Dans script/leek.js, vers la ligne 105 : 
```js
	new Chartist.Line('.ct-chart', data, {
		height: 130, // ps: dans la doc, ils mettent '130px'
		showArea: true,
		fullWidth: true,
		fullHeight: true, // ps: je n'ai pas trouvé cette option dans la doc
		axisX: {
			labelOffset: {
			  x: -23,
			  y: 0
			}
		}
	});
```
Et ça donne ceci, ce qui est pas mal : 
![image](https://cloud.githubusercontent.com/assets/12863317/21297924/e8839f04-c588-11e6-8169-a55af0e3873f.png)
J'ai rapidement testé le responsive, ça colle plutôt bien

Du coup j'ai regardé le code html et j'ai vu ceci. Notez que le dernier élément (qui est le dernier label), ne fait que 20px de large alors que les autres font 49pixels de large.
![image](https://cloud.githubusercontent.com/assets/12863317/21297931/03686f48-c589-11e6-890b-25668fc3f73c.png)

J'en ai conclus que le problème vient de la librairie. Et le labelOffset est le seul fix que j'ai pu trouvé

**Comment by 5pilow** [comment]
Je l'ai fixé autrement, dans https://github.com/leek-wars/leek-wars-client/commit/9278c27891beaef066ac5aa0d0dfcc417ba7154c
