### ISSUE TITLE
[BR] Poireau avec le skin d'un autre poireau

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#96]
![image](https://cloud.githubusercontent.com/assets/12863317/20859155/f68cd8ce-b956-11e6-8a32-a9b4e52f22dd.png)

1. Je rejoinds un BR
2. J'ai attendu environ 5 minutes
3. 2 poireaux sont arrivés en même temps et le bug s'est produit

Voici les vrais skin en temps normal : 
![image](https://cloud.githubusercontent.com/assets/12863317/20859171/5854fd20-b957-11e6-970c-5dba2ba8bef0.png)

**Comment by 5pilow** [comment]
Fixed in https://github.com/leek-wars/leek-wars-client/commit/7448f8ea337faf138b06fa19b57296ccf55e742a
